src/Entity/Equipe.php
<?php

namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EquipeRepository::class)]
class Equipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $logo = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    /**
     * @var Collection<int, Rencontre>
     */
    #[ORM\OneToMany(targetEntity: Rencontre::class, mappedBy: 'equipe_domicile')]
    private Collection $rencontres;

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'equipe')]
    private Collection $users;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $information_generale = null;

    public function __construct()
    {
        $this->rencontres = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Rencontre>
     */
    public function getRencontres(): Collection
    {
        return $this->rencontres;
    }

    public function addRencontre(Rencontre $rencontre): static
    {
        if (!$this->rencontres->contains($rencontre)) {
            $this->rencontres->add($rencontre);
            $rencontre->setEquipeDomicile($this);
        }

        return $this;
    }

    public function removeRencontre(Rencontre $rencontre): static
    {
        if ($this->rencontres->removeElement($rencontre)) {
            // set the owning side to null (unless already changed)
            if ($rencontre->getEquipeDomicile() === $this) {
                $rencontre->setEquipeDomicile(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setEquipe($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getEquipe() === $this) {
                $user->setEquipe(null);
            }
        }

        return $this;
    }

    public function getInformationGenerale(): ?string
    {
        return $this->information_generale;
    }

    public function setInformationGenerale(?string $information_generale): static
    {
        $this->information_generale = $information_generale;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\Position;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Cet email existe déjà')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\NotBlank(message:'Ce champ est obligatoire')]
    #[Assert\Email(message:"L'email doit être valide")]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Ce champ est obligatoire')]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:'Ce champ est obligatoire')]
    private ?string $firstname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birthdate = null;

    #[ORM\Column(nullable: true)]
    private ?int $height = null;

    #[ORM\Column(nullable: true)]
    private ?int $weight = null;

    #[ORM\Column(nullable: true)]
    private ?int $jersey_number = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $profil_picture = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true, enumType: Position::class)]
    private ?Position $position = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Equipe $equipe = null;

    /**
     * @var Collection<int, But>
     */
    #[ORM\OneToMany(targetEntity: But::class, mappedBy: 'user')]
    private Collection $buts;

    /**
     * @var Collection<int, Participation>
     */
    #[ORM\OneToMany(targetEntity: Participation::class, mappedBy: 'user')]
    private Collection $participations;

    /**
     * @var Collection<int, Assistance>
     */
    #[ORM\OneToMany(targetEntity: Assistance::class, mappedBy: 'user')]
    private Collection $assistances;

    public function __construct()
    {
        $this->buts = new ArrayCollection();
        $this->participations = new ArrayCollection();
        $this->assistances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(?\DateTimeInterface $birthdate): static
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(?int $height): static
    {
        $this->height = $height;

        return $this;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(?int $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    public function getJerseyNumber(): ?int
    {
        return $this->jersey_number;
    }

    public function setJerseyNumber(?int $jersey_number): static
    {
        $this->jersey_number = $jersey_number;

        return $this;
    }

    public function getProfilPicture(): ?string
    {
        return $this->profil_picture;
    }

    public function setProfilPicture(?string $profil_picture): static
    {
        $this->profil_picture = $profil_picture;

        // if (null !== $profil_picture) {
        //     // It is required that at least one field changes if you are using doctrine
        //     // otherwise the event listeners won't be called and the file is lost
        //     $this->updated_at = new \DateTimeImmutable();
        // }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getPosition(): ?Position
    {
        return $this->position;
    }

    public function setPosition(?Position $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getEquipe(): ?Equipe
    {
        return $this->equipe;
    }

    public function setEquipe(?Equipe $equipe): static
    {
        $this->equipe = $equipe;

        return $this;
    }

    /**
     * @return Collection<int, But>
     */
    public function getButs(): Collection
    {
        return $this->buts;
    }

    public function addBut(But $but): static
    {
        if (!$this->buts->contains($but)) {
            $this->buts->add($but);
            $but->setUser($this);
        }

        return $this;
    }

    public function removeBut(But $but): static
    {
        if ($this->buts->removeElement($but)) {
            // set the owning side to null (unless already changed)
            if ($but->getUser() === $this) {
                $but->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Participation>
     */
    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Participation $participation): static
    {
        if (!$this->participations->contains($participation)) {
            $this->participations->add($participation);
            $participation->setUser($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $participation): static
    {
        if ($this->participations->removeElement($participation)) {
            // set the owning side to null (unless already changed)
            if ($participation->getUser() === $this) {
                $participation->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Assistance>
     */
    public function getAssistances(): Collection
    {
        return $this->assistances;
    }

    public function addAssistance(Assistance $assistance): static
    {
        if (!$this->assistances->contains($assistance)) {
            $this->assistances->add($assistance);
            $assistance->setUser($this);
        }

        return $this;
    }

    public function removeAssistance(Assistance $assistance): static
    {
        if ($this->assistances->removeElement($assistance)) {
            // set the owning side to null (unless already changed)
            if ($assistance->getUser() === $this) {
                $assistance->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/EquipeController.php
<?php

namespace App\Controller;

use App\Entity\Equipe;
use App\Entity\User;
use App\Repository\EquipeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class EquipeController extends AbstractController
{
    #[Route('/equipes', name: 'equipe_liste')]
    public function equipeListe(EquipeRepository $equipeRepository): Response
    {
        $equipes = $equipeRepository->findAll();

        return $this->render('equipe/equipe_liste.html.twig', [
            'controller_name' => 'LoisirsProspects - Equipes',
            'equipes' => $equipes,
        ]);
    }

    #[Route('/equipe/{id}', name: 'equipe_details')]
    public function equipeDetails(Equipe $equipe): Response
    {
        $users = $equipe->getUsers();

        return $this->render('equipe/equipe_details.html.twig', [
            'controller_name' => 'LoisirsProspects - Equipes',
            'equipe' => $equipe,
            'users' => $users,
        ]);
    }

    #[Route('/mon_equipe', name: 'mon_equipe')]
    public function monEquipe(): Response
    {
        $user = $this->getUser();

        if (!$user instanceof User) {
            throw $this->createNotFoundException("Utilisateur non trouvé.");
        }

        $equipe = $user->getEquipe();
        $users = $equipe->getUsers();

        return $this->render('equipe/mon_equipe.html.twig', [
            'equipe' => $equipe,
            'users' => $users,
            'controller_name' => 'LoisirsProspects - Mon Equipe',
        ]);
    }
}

templates/equipe/equipe.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{controller_name}}
{% endblock %}

{% block body %}
	{% include 'assets/header.html.twig' %}

	<main>
		<div class="container-fluid pt-4">
			<h1>{{equipe.nom}}</h1>

			<!-- Pills navs -->
			<ul class="nav nav-pills nav-justified mb-4" id="ex1" role="tablist">
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link active" id="info_generales" href="#_info_generales" role="tab" aria-controls="info_generales" aria-selected="true">Informations générales</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="calendrier_resultat" href="#_calendrier_resultat" role="tab" aria-controls="calendrier_resultat" aria-selected="true">Calendrier / Résultats</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="effectif" href="#_effectif" role="tab" aria-controls="effectif" aria-selected="false">Effectif</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="stats_indiv" href="#_stats_indiv" role="tab" aria-controls="stats_indiv" aria-selected="false">Statistiques individuelles</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="stats_collectives" href="#_stats_collectives" role="tab" aria-controls="stats_collectives" aria-selected="false">Statistiques collectives</a>
				</li>
			</ul>
			<hr class="hr hr-blurry"/>
			<!-- Pills navs -->

			<!-- Pills content -->
            <div class="tab-content" id="ex2-content"> 

                <div class="tab-pane fade show active" id="_info_generales" role="tabpanel" aria-labelledby="info_generales">
                    info_generales content
                </div>

                <div class="tab-pane fade" id="_calendrier_resultat" role="tabpanel" aria-labelledby="calendrier_resultat">
                    calendrier_resultat content
                </div>

                <div class="tab-pane fade" id="_effectif" role="tabpanel" aria-labelledby="effectif">
                    <table id="usersTable" class="hover row-border w-100 stripe">
                        <thead>
                            <tr>
                                <th scope="col">Prenom</th>
                                <th scope="col">Nom</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in equipe.users %}
                                <tr>
                                    <td>{{ user.firstname }}</td>
                                    <td>{{ user.name }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="tab-pane fade" id="_stats_indiv" role="tabpanel" aria-labelledby="stats_indiv">
                    stats_indiv content
                </div>

                <div class="tab-pane fade" id="_stats_collectives" role="tabpanel" aria-labelledby="stats_collectives">
                    stats_collectives content
                </div>
            </div>
			<!-- Pills content -->
		</div>
	</main>

    	<script>
		$('#usersTable').DataTable({
			responsive: true,
			language: {
			info: 'Affichage de la page _PAGE_ sur _PAGES_',
			infoEmpty: 'Aucun enregistrement disponible',
			infoFiltered: '(filtré à partir de _MAX_ enregistrements au total)',
			lengthMenu: 'Afficher _MENU_ lignes par page',
			zeroRecords: 'Aucun résultat trouvé',
			search: 'Rechercher:'
		    }
		});
	</script>

{% endblock %}


templates/equipe/equipe_details.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{controller_name}}
{% endblock %}

{% block body %}
	{% include 'assets/header.html.twig' %}

	<main>
		<div class="container-fluid pt-4">
			<h1>{{equipe.nom}}</h1>

			<!-- Pills navs -->
			<ul class="nav nav-pills nav-justified mb-4" id="ex1" role="tablist">
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link active" id="info_generales" href="#_info_generales" role="tab" aria-controls="info_generales" aria-selected="true">Informations générales</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="calendrier_resultat" href="#_calendrier_resultat" role="tab" aria-controls="calendrier_resultat" aria-selected="true">Calendrier / Résultats</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="effectif" href="#_effectif" role="tab" aria-controls="effectif" aria-selected="false">Effectif</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="stats_indiv" href="#_stats_indiv" role="tab" aria-controls="stats_indiv" aria-selected="false">Statistiques individuelles</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="stats_collectives" href="#_stats_collectives" role="tab" aria-controls="stats_collectives" aria-selected="false">Statistiques collectives</a>
				</li>
			</ul>
			<hr class="hr hr-blurry"/>
			<!-- Pills navs -->

			<!-- Pills content -->
            <div class="tab-content" id="ex2-content"> 

                <div class="tab-pane fade show active" id="_info_generales" role="tabpanel" aria-labelledby="info_generales">
					{% include 'vue_commune/information_generale.html.twig' %}
                </div>

                <div class="tab-pane fade" id="_calendrier_resultat" role="tabpanel" aria-labelledby="calendrier_resultat">
                    calendrier_resultat content
                </div>

                <div class="tab-pane fade" id="_effectif" role="tabpanel" aria-labelledby="effectif">
					<div class="table-responsive">
						<table id="usersTable" class="display w-100">
							<thead>
								<tr>
									<th scope="col">Prenom</th>
									<th scope="col">Nom</th>
								</tr>
							</thead>
							<tbody>
								{% for user in equipe.users %}
									<tr>
										<td>{{ user.firstname }}</td>
										<td>{{ user.name }}</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
                </div>

                <div class="tab-pane fade" id="_stats_indiv" role="tabpanel" aria-labelledby="stats_indiv">
					{% include 'vue_commune/equipe_statistique_individuelle.html.twig' %}
                </div>

                <div class="tab-pane fade" id="_stats_collectives" role="tabpanel" aria-labelledby="stats_collectives">
                    stats_collectives content
                </div>
            </div>
			<!-- Pills content -->
		</div>
	</main>

    	<script>
		$('#usersTable').DataTable({
			language: {
				info: 'Affichage de la page _PAGE_ sur _PAGES_',
				infoEmpty: 'Aucun enregistrement disponible',
				infoFiltered: '(filtré à partir de _MAX_ enregistrements au total)',
				lengthMenu: 'Afficher _MENU_ lignes par page',
				zeroRecords: 'Aucun résultat trouvé',
				search: 'Rechercher:'
		    }
		});
	</script>

{% endblock %}


templates/equipe/equipe_liste.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{controller_name}} {% endblock %}

{% block body %}
{% include 'assets/header.html.twig' %}

  <main>
    <div class="container pt-4">

      <h1>Equipes du championnat</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium ex tempore libero labore quod a, nam
        necessitatibus quam eligendi sequi quos deserunt, esse nulla possimus minima velit cumque? Voluptate, ipsum.</p>

      {% for equipe in equipes %}

        <a href="{{ path('equipe_details', {id:equipe.id}) }}"><h2>{{equipe.nom}}</h2></a>

      {% endfor %}

    </div>
  </main>
{% endblock %}

templates/equipe/equipes.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{controller_name}} {% endblock %}

{% block body %}
{% include 'assets/header.html.twig' %}

  <main>
    <div class="container pt-4">

      <h1>Equipes du championnat</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium ex tempore libero labore quod a, nam
        necessitatibus quam eligendi sequi quos deserunt, esse nulla possimus minima velit cumque? Voluptate, ipsum.</p>

      {% for equipe in equipes %}

        <a href="{{ path('equipe', {id:equipe.id}) }}"><h2>{{equipe.nom}}</h2></a>

      {% endfor %}

    </div>
  </main>
{% endblock %}

templates/equipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
{% include 'assets/header.html.twig' %}

  <main>
    <div class="container pt-4">

      <h1>Equipes</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium ex tempore libero labore quod a, nam
        necessitatibus quam eligendi sequi quos deserunt, esse nulla possimus minima velit cumque? Voluptate, ipsum.</p>

    </div>
  </main>
{% endblock %}

templates/equipe/mon_equipe.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{controller_name}}
{% endblock %}

{% block body %}
	{% include 'assets/header.html.twig' %}

	<main>
		<div class="container-fluid pt-4">
			<h1>Mon Equipe</h1>
			<!-- Pills navs -->
			<ul class="nav nav-pills nav-justified mb-4" id="ex1" role="tablist">
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link active" id="info_generales" href="#_info_generales" role="tab" aria-controls="info_generales" aria-selected="true">Informations générales</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="effectif" href="#_effectif" role="tab" aria-controls="effectif" aria-selected="false">Effectif</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="stats_indiv" href="#_stats_indiv" role="tab" aria-controls="stats_indiv" aria-selected="false">Statistiques individuelles</a>
				</li>
				<li class="nav-item" role="presentation">
					<a data-mdb-pill-init class="nav-link" id="stats_collectives" href="#_stats_collectives" role="tab" aria-controls="stats_collectives" aria-selected="false">Statistiques collectives</a>
				</li>
			</ul>
			<hr class="hr hr-blurry" />
			<!-- Pills navs -->

			<!-- Pills content -->
			<div class="tab-content" id="ex2-content">
				<div class="tab-pane fade show active" id="_info_generales" role="tabpanel" aria-labelledby="info_generales">
					{% include 'vue_commune/information_generale.html.twig' %}
				</div>
				<div class="tab-pane fade" id="_effectif" role="tabpanel" aria-labelledby="effectif">
					<div class="table-responsive">
						<table id="usersTable" class="display w-100">
							<thead>
								<tr>
									<th scope="col">N°</th>
									<th scope="col">Photo</th>
									<th scope="col">Joueur</th>
									<th scope="col">Pos</th>
									<th scope="col">Taille</th>
									<th scope="col">Poids</th>
									<th scope="col">Né le</th>
									<th scope="col">Lancer</th>
									<th scope="col">Nationnalité</th>
								</tr>
							</thead>
							<tbody>
								{% for user in users %}
									<tr>
										<td>{{ user.jerseyNumber }}</td>
										<td>{{ user.profilPicture }}</td>
										<td>{{ user.firstname }} {{ user.name }}</td>
										<td>{{ user.position.value }}</td>
										<td>{{ user.height }}</td>
										<td>{{ user.weight }}</td>
										<td>{{ user.birthdate|date('Y') }}</td>
										<td>Todo</td>
										<td>Todo</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				<div class="tab-pane fade" id="_stats_indiv" role="tabpanel" aria-labelledby="stats_indiv">
					{% include 'vue_commune/equipe_statistique_individuelle.html.twig' %}
				</div>
				<div class="tab-pane fade" id="_stats_collectives" role="tabpanel" aria-labelledby="stats_collectives">
					stats_collectives content
				</div>
			</div>
			<!-- Pills content -->

		</div>
	</main>

	<script>
		$('#usersTable').DataTable({
			language: {
				info: 'Affichage de la page _PAGE_ sur _PAGES_',
				infoEmpty: 'Aucun enregistrement disponible',
				infoFiltered: '(filtré à partir de _MAX_ enregistrements au total)',
				lengthMenu: 'Afficher _MENU_ lignes par page',
				zeroRecords: 'Aucun résultat trouvé',
				search: 'Rechercher:'
			}
		});
	</script>
{% endblock %}
